apiVersion: v1
kind: Service
metadata:
  name: trocr-service
  namespace: default
  labels:
    app: trocr-service
spec:
  selector:
    app: trocr-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
